Cleanup

diff --git a/ansible/roles/backend/files/twctl b/ansible/roles/backend/files/twctl
--- a/ansible/roles/backend/files/twctl
+++ b/ansible/roles/backend/files/twctl
@@ -16,6 +16,41 @@ fi
 CONFIG_FILE="${ANSIBLE_DIR}/group_vars/all"
 CLUSTER_CONFIG_DIR=/data/cluster_config
 
+if [ -d "$CLUSTER_CONFIG_DIR" ] ; then
+	# Clustered setup
+	INSTALLATION=cluster
+	VAULT_ADDR="https://vault.service.consul:8200"
+
+	if [ "$UID" != "0" ] && [ ! -r "$CLUSTER_CONFIG_DIR" ] ; then
+		# Try to grant read permissions to the required files
+		sudo chgrp -R teamwire "$CLUSTER_CONFIG_DIR"
+	fi
+
+	NOMAD_JOB="${CLUSTER_CONFIG_DIR}/teamwire.nomad"
+	NOMAD="/usr/local/bin/nomad"
+else
+	# Single server installation
+	INSTALLATION=single
+	VAULT_ADDR="https://127.0.0.1:8200"
+
+	if [ ! -f "$CONFIG_FILE" ]; then
+		echo "ERROR: Missing configuration file ${CONFIG_FILE}!"
+		echo "       Please configure the server before using this tool."
+		exit 1
+	fi
+
+	CONTAINERS="teamwire_screenshot_server teamwire_notification_server teamwire_beat teamwire_worker teamwire_backend"
+fi
+
+IMAGES="teamwire/backend teamwire/web-screenshot-server teamwire/notification-server"
+
+VAULT_INITIALIZED=$(curl -s "${VAULT_ADDR}/v1/sys/health" | jq '.initialized')
+VAULT_SEALED=$(curl -s "${VAULT_ADDR}/v1/sys/health" | jq '.sealed')
+
+if [ "$VAULT_INITIALIZED" == "true" ] && [ "$VAULT_SEALED" != "false" ] && [[ $2 -ne "unseal" || $2 -ne "rescue" ]]; then
+	echo "Vault must be unsealed. Please run twctl secrets unseal."
+	exit 1
+fi
 
 get_vault_secret_recursive() {
         vault_list="vault list -format "yaml" secret"
@@ -74,42 +109,6 @@ _get_config_value() {
 	local ENTRY="$1"
 	awk '/^'${ENTRY}':/ { gsub("(^\"|\"$)","", $2); print $2 }' "$CONFIG_FILE" 2> /dev/null
 }
-
-if [ -d "$CLUSTER_CONFIG_DIR" ] ; then
-	# Clustered setup
-	INSTALLATION=cluster
-	VAULT_ADDR="https://vault.service.consul:8200"
-
-	if [ "$UID" != "0" ] && [ ! -r "$CLUSTER_CONFIG_DIR" ] ; then
-		# Try to grant read permissions to the required files
-		sudo chgrp -R teamwire "$CLUSTER_CONFIG_DIR"
-	fi
-
-	NOMAD_JOB="${CLUSTER_CONFIG_DIR}/teamwire.nomad"
-	NOMAD="/usr/local/bin/nomad"
-else
-	# Single server installation
-	INSTALLATION=single
-	VAULT_ADDR="https://127.0.0.1:8200"
-
-	if [ ! -f "$CONFIG_FILE" ]; then
-		echo "ERROR: Missing configuration file ${CONFIG_FILE}!"
-		echo "       Please configure the server before using this tool."
-		exit 1
-	fi
-
-	CONTAINERS="teamwire_screenshot_server teamwire_notification_server teamwire_beat teamwire_worker teamwire_backend"
-fi
-
-IMAGES="teamwire/backend teamwire/web-screenshot-server teamwire/notification-server"
-
-VAULT_INITIALIZED=$(curl -s "${VAULT_ADDR}/v1/sys/health" | jq '.initialized')
-VAULT_SEALED=$(curl -s "${VAULT_ADDR}/v1/sys/health" | jq '.sealed')
-
-if [ "$VAULT_INITIALIZED" == "true" ] && [ "$VAULT_SEALED" != "false" ] && [[ $2 -ne "unseal" || $2 -ne "rescue" ]]; then
-	echo "Vault must be unsealed. Please run twctl secrets unseal."
-	exit 1
-fi
 
 check_tag() {
 	local TAG=$1
